# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: centos:7
    environment:
      - PATH: /usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - BUILD_GOLANG_VERSION: 1.19.1
    steps:
      - run:
          name: Install Dependencies
          command: yum install -y git make
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Setup Go
          command: make setup_go_linux
      - run:
          name: Install Go Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run unit tests
          command: make unittest
      - run:
          name: Run e2e tests
          command: make e2etest
      - store_test_results:
          path: /tmp/test-reports
